<a href="https://colab.research.google.com/github/uppercasee/GoogleColab/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
torch.__version__

'2.0.1+cu118'

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6796, 0.7516, 0.5158],
        [0.7816, 0.7081, 0.8715],
        [0.3159, 0.9344, 0.0196],
        [0.6846, 0.4717, 0.7167],
        [0.0481, 0.4133, 0.3094]])


In [6]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# Getting tensor back as a python int
scalar.item()

7

In [10]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
# Check shape of vector
vector.shape

torch.Size([2])

In [13]:
# Matrix
MATRIX = torch.tensor([[7, 8, 1], 
                       [9, 10, 4]])
MATRIX

tensor([[ 7,  8,  1],
        [ 9, 10,  4]])

In [14]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 3]))

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3,4],
                        [3, 6, 9,4],
                        [2, 4, 5,4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 4, 5, 4]]])

In [16]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 4]))

In [17]:
NEW = torch.tensor([[[1,2],
                     [3,4],
                     [5,6]]])
NEW

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [18]:
NEW.ndim, NEW.shape

(3, torch.Size([1, 3, 2]))

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[0.0193, 0.1483, 0.4730, 0.2909],
         [0.7792, 0.1174, 0.0180, 0.0755],
         [0.8493, 0.6367, 0.6744, 0.9261]]),
 torch.float32,
 2)

In [20]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
zero = torch.zeros(3,3)
zero, zero.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [22]:
one = torch.ones(3,3)
one, one.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [28]:
one_to_ten = torch.arange(1,1000, 77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [33]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3940, 0.6026, 0.4934, 0.8533],
        [0.4317, 0.6633, 0.4762, 0.8479],
        [0.6695, 0.0249, 0.8908, 0.6832]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [41]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [42]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [49]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [44]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [50]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [54]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")
y = x.type(torch.float32)
x,y

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]))