<a href="https://colab.research.google.com/github/uppercasee/GoogleColab/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
torch.__version__

'2.0.1+cu118'

In [24]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1858, 0.4878, 0.8576],
        [0.8509, 0.0910, 0.1158],
        [0.5408, 0.9876, 0.1317],
        [0.4857, 0.8514, 0.1649],
        [0.3614, 0.4698, 0.0620]])


In [25]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [26]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim

0

In [28]:
# Getting tensor back as a python int
scalar.item()

7

In [29]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [30]:
vector.ndim

1

In [31]:
# Check shape of vector
vector.shape

torch.Size([2])

In [32]:
# Matrix
MATRIX = torch.tensor([[7, 8, 1], 
                       [9, 10, 4]])
MATRIX

tensor([[ 7,  8,  1],
        [ 9, 10,  4]])

In [33]:
MATRIX.ndim

2

In [34]:
MATRIX.shape

torch.Size([2, 3])

In [35]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3,4],
                        [3, 6, 9,4],
                        [2, 4, 5,4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 4, 5, 4]]])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.shape

torch.Size([1, 3, 4])