<a href="https://colab.research.google.com/github/uppercasee/GoogleColab/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
torch.__version__

'2.0.1+cu118'

In [24]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1858, 0.4878, 0.8576],
        [0.8509, 0.0910, 0.1158],
        [0.5408, 0.9876, 0.1317],
        [0.4857, 0.8514, 0.1649],
        [0.3614, 0.4698, 0.0620]])


In [25]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [26]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim

0

In [28]:
# Getting tensor back as a python int
scalar.item()

7

In [29]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [30]:
vector.ndim

1

In [31]:
# Check shape of vector
vector.shape

torch.Size([2])

In [32]:
# Matrix
MATRIX = torch.tensor([[7, 8, 1], 
                       [9, 10, 4]])
MATRIX

tensor([[ 7,  8,  1],
        [ 9, 10,  4]])

In [46]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 3]))

In [35]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3,4],
                        [3, 6, 9,4],
                        [2, 4, 5,4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 4, 5, 4]]])

In [45]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 4]))

In [38]:
NEW = torch.tensor([[[1,2],
                     [3,4],
                     [5,6]]])
NEW

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [44]:
NEW.ndim, NEW.shape

(3, torch.Size([1, 3, 2]))

In [60]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[0.7217, 0.1998, 0.8643, 0.2909],
         [0.7355, 0.4429, 0.1400, 0.1415],
         [0.2801, 0.3138, 0.8398, 0.6294]]),
 torch.float32,
 2)

In [55]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [65]:
zero = torch.zeros(3,3)
zero, zero.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [64]:
one = torch.ones(3,3)
one, one.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)