<a href="https://colab.research.google.com/github/uppercasee/GoogleColab/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7212, 0.5728, 0.3015],
        [0.6794, 0.7100, 0.5837],
        [0.5634, 0.7326, 0.9720],
        [0.8616, 0.9044, 0.7677],
        [0.6087, 0.5057, 0.8047]])


In [4]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Getting tensor back as a python int
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
# Check shape of vector
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7, 8, 1],
                       [9, 10, 4]])
MATRIX

tensor([[ 7,  8,  1],
        [ 9, 10,  4]])

In [12]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 3]))

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3,4],
                        [3, 6, 9,4],
                        [2, 4, 5,4]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [3, 6, 9, 4],
         [2, 4, 5, 4]]])

In [14]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 4]))

In [15]:
NEW = torch.tensor([[[1,2],
                     [3,4],
                     [5,6]]])
NEW

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [16]:
NEW.ndim, NEW.shape

(3, torch.Size([1, 3, 2]))

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[0.9335, 0.1957, 0.5693, 0.9635],
         [0.9817, 0.9891, 0.6291, 0.7680],
         [0.5835, 0.1521, 0.5582, 0.3862]]),
 torch.float32,
 2)

In [18]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zero = torch.zeros(3,3)
zero, zero.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [20]:
one = torch.ones(3,3)
one, one.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [21]:
one_to_ten = torch.arange(1,1000, 77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [22]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [24]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3875, 0.7091, 0.6453, 0.3102],
        [0.0027, 0.6264, 0.4429, 0.9837],
        [0.1574, 0.4713, 0.8252, 0.6294]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [25]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [26]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [27]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [28]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [29]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [30]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")
y = x.type(torch.float32)
x,y

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [31]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [32]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [33]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [34]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [35]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [40]:
# Change the array, keep the tensor
array = array + 1
array, tensor


(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [41]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [42]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))